name: Release

on:
  push:
    branches:
      - main

jobs:
  dockerfile-test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Npm install
        run: sudo bash scripts/npm-install.sh

      - name: Build image
        run: make build

      - name: Test image
        run: make test

      - name: Display all docker images
        if: always()
        run: docker images

      - name: Login to Docker Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          # We push to the default registry currently. If you want to push to a different registry,
          # uncomment the line below.
          # login-server: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REG_USERNAME }}
          password: ${{ secrets.DOCKER_REG_PASSWORD }}

      - name: Docker Hub Description
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_REG_USERNAME }}
          password: ${{ secrets.DOCKER_REG_PASSWORD }}
          repository: ambimax/bats

      - name: Push image
        if: github.ref == 'refs/heads/main'
        run: make push
