name: Tests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  dockerfile-test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build image
        run: make build

      - name: Test image
        run: make test

      - name: Display all docker images
        if: always()
        run: docker images
